### ISSUE TITLE
[Indigo] Sprint 3 Roadmap (03/11/2022 - 03/24/2022)

### ISSUE THREAD

**Issue by lilingxi01** [david-fisher/320-S22-Track2#45]
# Description

Our main goal for this sprint is to bring the filter into reality and also finish building up necessary components.

**Code base branch:** `indigo-dev`.

**IMPORTANT:** Create a new branch based on this branch and have a name in this format: `indigo-dev-[your_first_name]`. [Check development standards](https://github.com/david-fisher/320-S22-Track2/wiki/Indigo-·-Development-Standards). If you are having trouble doing this, feel free to ask me!

In the end of this sprint, we are going to merge our completed progress into the branch `indigo-dev` to make the demo.

# Roadmap Checklist

- [x] **3001. BPDatePickerComponent dropdown prototype** - @lilingxi01 
  - Going to implement next week: Shortcut commands.
- [x] **3002. BPDomainSelectionComponent dropdown prototype** - @lilingxi01 
  - Going to implement next week: Tab indexes.
- [x] **3003. BPSeveritySelectionComponent prototype** - @lilingxi01 
- [x] **3004. BPRootView prototype with adjustable bar (internal prototype)** - @aishwaryar12309 , @efathalizade 
- [x] ~~**3005. BPActivityTableComponent prototype**~~ - @srinaldi-umass , @lilingxi01 
  - This is moved to the next sprint for a work load consideration.
- [x] **3006. Implement the Expand All and Collapse All functionalities** - @limbo-yan , @nekomi2 
- [x] ~~**3007. BPTreeFilterComponent state values integration**~~ - @lilingxi01 , @limbo-yan 
  - This is moved to the sprint when we are finally integrating the values between TreeFilter and TreeMap.
- [x] ~~**3008. BPActivityFilterComponent state values integration**~~ - @lilingxi01 , @srinaldi-umass 
  - This is moved to the sprint when we are finally integrating the values between ActivityFilter and ActivityTable.
- [x] ~~**3009. Setup launchpad for data fetching procedure**~~ - @lilingxi01 
  - The deadline of this goal is moved to the next sprint because we are not interacting with data right now.
- [x] **3010. Rebuild the tree component with MUI tree view** - @nekomi2 , @lilingxi01

**Comment by lilingxi01** [comment]
Great job in the last week, everyone!
